name: .net tests


on:
  push:
    branches: [ "main" ]
 
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build docker image
      run: docker build --build-arg GH_USERNAME=${{ secrets.GH_USERNAME }} --build-arg GH_TOKEN=${{ secrets.GITHUB_TOKEN }} -t ${{ secrets.DOCKER_HUB_USERNAME }}/chethana:${{ github.sha }} .
    - name: Docker push
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/chethana:${{ github.sha }}
      
         
  tests:
    runs-on: ubuntu-latest
    container:
      image: ubandc2/chethana:${{ github.sha }}
    steps: 
    - name: Start service
      run: |
           cd /usr/src/app
           dotnet dev-certs https
           dotnet dev-certs https --trust
           dotnet run -p CardValidation.Web/CardValidation.Web.csproj & dotnet test
           
    needs: 
      - docker_build 
